name: 股票数据获取定时任务

on:
  schedule:
    # 每个工作日上午9:27执行 (UTC时间，北京时间需要减8小时，所以是1:27)
    - cron: '27 1 * * 1-5'
  # 允许手动触发
  workflow_dispatch:

jobs:
  fetch-stock-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 执行股票数据获取脚本
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
        THS_COOKIE: ${{ secrets.THS_COOKIE }}
      run: python fetch_stock_data.py
      
    - name: 上传执行结果
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: stock-data-logs
        path: |
          *.xlsx
          *.log
        retention-days: 7